input_features:
- name: Pclass
  type: numerical
- name: Sex
  type: category
- name: Age
  type: numerical
  preprocessing:
          missing_value_strategy: fill_with_mean
          normalization: zscore  
- name: SibSp
  type: numerical
- name: Parch
  type: numerical
- name: Ticket
  type: category
- name: Fare
  type: numerical
- name: Cabin
  type: category
output_features:
- name: Survived
  type: binary
  num_fc_layers: 2
  fc_size: 128
training:
    batch_size: 32
    epochs: 200
